#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#define STB_VOXEL_RENDER_IMPLEMENTATION
#define STBVOX_CONFIG_MODE 1
#define STBVOX_CONFIG_DISABLE_TEX2
#define STBVOX_CONFIG_PREFER_TEXBUFFER

#include "stb_voxel_render.h"
